# Default state for all rules
default: true

# Path to configuration file to extend
extends: null

MD007:
  # Spaces for indent
  indent: 4

MD012:
  # Consecutive blank lines
  maximum: 3

MD013: false

MD033: false

MD034: false

MD037: false

MD049: false

MD046: false
