[tool.poetry]
name = "deep-learning"
version = "0.1.0"
description = "Time Series Forecasting with Deep Learning"
authors = ["LM <hi@leima.is>"]
readme = "README.md"
packages = [{include = "ts_dl_utils"}]

[tool.poetry.dependencies]
python = "^3.9"
mkdocs-material = "9.0.12"
mkdocs-autorefs = "0.4.1"
mkdocstrings = "0.19.0"
mkdocs-with-pdf = "0.9.3"
mkdocs-git-authors-plugin = "0.6.4"
mkdocs-bibtex = "2.8.1"


[tool.poetry.group.darts.dependencies]
darts = "^0.24.0"

[tool.poetry.group.notebook.dependencies]
ipykernel = "^6.21.1"
jupytext = "^1.14.5"


[tool.poetry.group.visualization.dependencies]
seaborn = "^0.12.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
