name: Publish Docs with PDF

on:
#   push:
#     branches:
#       - master
#       - main
  workflow_dispatch:
    inputs:
      directory:
        description: 'Release it'
        default: 'gogogo'
        required: false


jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: nikeee/setup-pandoc@v1
      - run: google-chrome --version
      - run: echo $(which chrome)
      - run: sudo apt update && sudo apt install python3-cffi python3-brotli libpango-1.0-0 libpangoft2-1.0-0
      - run: pip install -r requirements.txt
      - run: export ENABLE_PDF_EXPORT=1 && mkdocs gh-deploy -f mkdocs.ubuntu.yml --force
